
sort:
	go run main.go

arr:
	g++ -Wall -Wextra generate.cpp -o gen
	./gen
	rm -rf gen
clean:
	rm -rf gen
	rm -rf r
	rm -rf f
	rm -rf ra
	rm -rf sr
	rm -rf s
	rm -rf si
cfunc:
	g++ qsort_test.cpp 
	./a.out
